name: API_REF

on:
  push:
    branches:
      - main
      - pydoctor
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Rye (in non-interactive mode)
      - name: Install Rye in non-interactive mode
        run: |
          export RYE_HOME=$HOME/.rye
          curl -sSf https://rye.astral.sh/get | bash -s -- --no-confirm

      # Step 3: Add Rye to the PATH
      - name: Add Rye to PATH
        run: echo "$HOME/.rye/shims:$HOME/.rye/bin" >> $GITHUB_PATH

      # Sync dependencies (including dev dependencies like PyDoctor)
      - name: Sync dev dependencies
        run: rye sync --dev

      # Generate the API documentation using PyDoctor
      - name: Build docs using PyDoctor
        run: |
          rye run pydoctor --config=docs/pydoctor.ini src/resonate

      # Archive the generated documentation for GitHub Pages
      - name: Archive artifact
        shell: sh
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --directory docs/build \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
          echo ::endgroup::

      # Upload the artifact for later deployment
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Deploy to GitHub Pages using the uploaded artifact
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
