name: ci

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - README.md
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md

jobs:
  run:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    env:
      RESONATE_HOST: http://localhost

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.12, 3.13]
        server-version: [main, latest]

    steps:
      - uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: 0.5.23

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: install
        run: uv sync --dev

      - name: check linting
        run: uv run ruff check

      - name: check types
        run: uv run pyright

      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          cache: false # turn caching off to avoid warning

      - name: Get latest Resonate release tag (if needed)
        if: matrix.server-version == 'latest'
        id: get-resonate-tag
        run: |
          LATEST_TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/resonatehq/resonate/releases/latest | jq -r .tag_name)
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: checkout resonate repository
        uses: actions/checkout@v4
        with:
          repository: resonatehq/resonate
          path: server
          ref: ${{ matrix.server-version == 'latest' && steps.get-resonate-tag.outputs.tag || 'main' }}

      - name: build resonate
        run: go build -o resonate
        working-directory: server

      - name: start resonate server
        run: ./resonate serve --system-signal-timeout 0.1s &
        working-directory: server

      - name: run tests with coverage
        id: coverage
        if: ${{ matrix.server-version == 'latest' && matrix.python-version == '3.13' && matrix.os == 'ubuntu-latest' && github.ref == 'refs/heads/main' }}
        run: uv run pytest --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        if: ${{ steps.coverage.outcome != 'skipped' }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: run tests
        if: ${{ steps.coverage.outcome == 'skipped' }}
        run: uv run pytest
